# Run vanilla and fine-tuned Laya on the test sets

This notebook loads the two checkpoints shipped in `checkpoints/` and asks both of them every question in the hand-labelled test sets:

- **Search routing:** 96 catalog queries. Does each one need the graph search? The spatial search?
- **First tool:** 42 held-out analysis requests. Which of 53 tools should run first?

It then shows the accuracy, every individual answer, and where the two models disagree. `laya_decision_models.ipynb` explains what a decision model is; this notebook only runs the models.

**Runtime:** about 1 minute on a GPU. On a 2-CPU machine it takes about 20 minutes, almost all of it the 53-option tool questions. Set `TOOL_LIMIT` below to run fewer.

In [1]:
import json, time, warnings
warnings.filterwarnings("ignore", message="IProgress not found")
from pathlib import Path

import pandas as pd
import torch
from laya.agent import Agent

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 70)

CHECKPOINTS = {"vanilla": Path("checkpoints/laya-vanilla"), "fine-tuned": Path("checkpoints/laya-finetuned")}
for d in CHECKPOINTS.values():
    w = d / "model.safetensors"
    assert w.exists() and w.stat().st_size > 10_000_000, f"{w} is missing or a Git LFS pointer: run `git lfs pull`"

QUESTIONS = json.loads(Path("data/questions.json").read_text(encoding="utf-8"))
# Each model is asked the router questions in the wording that suits it: the fine-tuned model the exact wording
# it was trained on, vanilla Laya the wording that scored best for it zero-shot.
ROUTER_WORDING = {"vanilla": QUESTIONS["router_zero_shot"], "fine-tuned": QUESTIONS["router_finetuned"]}
TOOL_Q = {"tool": QUESTIONS["tool"]}

read = lambda p: [json.loads(l) for l in open(p, encoding="utf-8") if l.strip()]
ROUTER_SET = read("data/eval/router_eval_queries.jsonl")
TOOL_SET = read("data/eval/tool_eval_holdout.jsonl")
TOOL_LIMIT = None          # e.g. 10 for a quick run on CPU

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {DEVICE} · {len(ROUTER_SET)} routing queries · {len(TOOL_SET[:TOOL_LIMIT])} tool requests")
print("\nrouter questions, as each model is asked them:")
for name, q in ROUTER_WORDING.items():
    print(f"  {name:10} graph:   {q['graph']['instructions']}\n  {'':10} spatial: {q['spatial']['instructions']}")

device: cuda · 96 routing queries · 42 tool requests

router questions, as each model is asked them:
  vanilla    graph:   Does this query name a specific person, organization or tag?
             spatial: Does this query mention a place or geographic location?
  fine-tuned graph:   Does this query name a specific person, organization or tag, ask what is popular, or ask for resources linked to another resource?
             spatial: Does this query mention a specific place, coordinates, or a distance or area on a map?

## Call the models

One model at a time is loaded, so peak memory stays at about 2.5 GB on CPU. Each routing query is one forward pass that answers both yes/no questions. Each tool request is one forward pass over all 53 options.

In [2]:
def run(name):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model = Agent(str(CHECKPOINTS[name]), device=DEVICE)
    t0 = time.perf_counter()
    router = model.predict_batch([r["query"] for r in ROUTER_SET], ROUTER_WORDING[name], batch_size=16)
    t1 = time.perf_counter()
    tools = model.predict_batch([f"{r['context']}\nRequest: {r['request']}" for r in TOOL_SET[:TOOL_LIMIT]], TOOL_Q,
                                batch_size=4 if DEVICE == "cuda" else 1, max_len=1600, head_max_len=1400)
    t2 = time.perf_counter()
    print(f"{name:10} routing: {(t1 - t0) / len(ROUTER_SET) * 1000:6.0f} ms/query · "
          f"tools: {(t2 - t1) / len(tools) * 1000:6.0f} ms/request")
    return {"router": [{f: a["answers"][f]["noul"] for f in ("graph", "spatial")} for a in router],
            "tools": [a["answers"]["tool"]["probabilities"] for a in tools]}


results = {}
for name in CHECKPOINTS:
    results[name] = run(name)

vanilla    routing:     17 ms/query · tools:    138 ms/request

fine-tuned routing:     12 ms/query · tools:    135 ms/request

## Search routing: accuracy

Scored on the 87 queries not marked ambiguous, with a cut-off of 0.5.

In [3]:
clear = [i for i, r in enumerate(ROUTER_SET) if not r.get("ambiguous")]
acc = {}
for name, res in results.items():
    pred = [{f: res["router"][i][f] >= 0.5 for f in ("graph", "spatial")} for i in range(len(ROUTER_SET))]
    acc[name] = {"graph accuracy": sum(pred[i]["graph"] == ROUTER_SET[i]["graph"] for i in clear) / len(clear),
                 "spatial accuracy": sum(pred[i]["spatial"] == ROUTER_SET[i]["spatial"] for i in clear) / len(clear),
                 "both right": sum(pred[i]["graph"] == ROUTER_SET[i]["graph"] and pred[i]["spatial"] == ROUTER_SET[i]["spatial"]
                                   for i in clear) / len(clear)}
pd.DataFrame(acc).T.round(3)

            graph accuracy  spatial accuracy  both right
vanilla              0.621             0.667       0.414
fine-tuned           0.954             0.989       0.943

## Search routing: every answer

Each cell shows P(yes); ✗ marks a disagreement with the gold label. Rows marked *amb.* are ambiguous and not scored.

In [4]:
def cell(p, gold):
    return f"{p:.2f}" + ("" if (p >= 0.5) == gold else " ✗")


rows = []
for i, r in enumerate(ROUTER_SET):
    row = {"query": r["query"][:70] + (" (amb.)" if r.get("ambiguous") else "")}
    for f in ("graph", "spatial"):
        row[(f, "gold")] = "yes" if r[f] else "no"
        for name in results:
            row[(f, name)] = cell(results[name]["router"][i][f], r[f])
    rows.append(row)
router_table = pd.DataFrame(rows).set_index("query")
router_table.columns = pd.MultiIndex.from_tuples(router_table.columns)
router_table

                                                                       graph  \
                                                                        gold
query
Which Chicago community areas have the poorest spatial accessibility t    no
Use the available flood-depth prediction resources to identify require    no
Find flood risk maps for Boone County, Iowa, compare available map yea    no
Build an OSM-based road network for a wildfire evacuation scenario and    no
Droughts in California                                                    no
Floods in Texas                                                           no
datasets about flooding in Illinois                                       no
water datasets                                                            no
Water quality datasets in California                                      no
What are the main sources of greenhouse gas emissions?                    no
What datasets exist for floods?                                           no
climate geospatial data                                                   no
flood risk geospatial datasets                                            no
geospatial datasets dams                                                  no
water resource management irrigation                                      no
publications by John Smith                                               yes
datasets from NASA                                                       yes
resources tagged climate                                                 yes
papers affiliated with USGS                                              yes
notebooks written by Shaowen Wang                                        yes
What has Anand Padmanabhan published on I-GUIDE?                         yes
most popular notebooks                                                   yes
trending datasets this month                                             yes
resources developed by the University of Illinois                        yes
datasets maintained by NOAA                                              yes
notebooks that use the SVI dataset                                       yes
what publications cite the CyberGIS-Compute paper?                       yes
show me resources related to element id 3f2a9c1e                         yes
who contributed the FireABM notebook?                                    yes
which organizations have uploaded the most datasets?                     yes
notebooks categorized as hydrology                                       yes
educational resources labeled machine learning                           yes
other datasets by the author of the SNAP dataset                         yes
notebooks connected to the Pysal Access publication                      yes
top viewed OERs                                                          yes
weather stations near Chicago                                             no
land cover data within 50 miles of Denver                                 no
datasets covering 40.1N, 88.2W                                            no
elevation data for the Grand Canyon                                       no
heat vulnerability in Phoenix neighborhoods                               no
crop yield data for the Midwest                                           no
hurricane damage along the Gulf Coast                                     no
air quality monitoring in Los Angeles County                              no
groundwater depletion in the Ogallala aquifer                             no
Sentinel-2 imagery over Nairobi                                           no
census tracts in Champaign County                                         no
wildfire perimeters in northern California 2020                           no
flood maps for the Mississippi River basin                                no
road networks in Paradise, CA                                             no
datasets for Springfield (amb.)                                           no
urban heat island studies in Asian megacities                             no
coastal erosion in Louisiana                                              no
snow cover data for the Rocky Mountains                                   no
NASA datasets about drought in Texas                                     yes
USGS streamflow data in Iowa                                             yes
notebooks by Shaowen Wang about Chicago                                  yes
NOAA precipitation datasets near Houston                                 yes
publications from the University of Illinois on Champaign flooding       yes
most popular datasets for California wildfires                           yes
resources tagged hydrology covering the Great Lakes                      yes
FEMA flood maps for Boone County, Iowa                                   yes
notebooks related to the Chicago hospital accessibility dataset          yes
USDA crop data for Illinois counties                                     yes
papers by Michael Goodchild on geographic information science            yes
what is spatial autocorrelation?                                          no
how do I compute NDVI from Sentinel-2 bands?                              no
machine learning for flood prediction                                     no
explain the two-step floating catchment area method                       no
datasets about social vulnerability                                       no
notebooks on deep learning for land cover classification                  no
compare kriging and inverse distance weighting                            no
resources about agent-based modeling of evacuation                        no
time series of global temperature anomalies (amb.)                        no
what is the clay embedding model?                                         no
tutorials for GeoPandas                                                   no
how does climate change affect crop yields?                               no
datasets similar to NLCD land cover (amb.)                               yes
open-source tools for hydrological modeling                               no
what is the capital of france?                                            no
what can you do with satellite imagery?                                   no
which embedding models do you have?                                       no
what resolution was that?                                                 no
show me the code                                                          no
can you handle GeoTIFF?                                                   no
Embed this drawn region with the gse model (amb.)                         no
buffer the hotspot by 2 km and show it on the map (amb.)                  no
flood risk geospatial analysis                                            no
I-GUIDE Smart Search                                                      no
Build an OSM-based road network for a wildfire evacuation scenario in     no
Rank areas that may face higher exposure to potential dam failure r...   yes
Acquire precipitation, temperature, wind, humidity, and evapotransp...    no
Explain and map major drivers of local water stress using the SIMPL...   yes
Map places where heat-related public sentiment or exposure overlaps...    no
Identify resources that can detect wildfire threat to transportation i    no
Use available biodiversity and land-use resources to summarize how ter    no
Generate a heat map of violent crime in Chicago.                          no

                                                                                \
                                                                       vanilla
query
Which Chicago community areas have the poorest spatial accessibility t    0.07
Use the available flood-depth prediction resources to identify require    0.03
Find flood risk maps for Boone County, Iowa, compare available map yea    0.00
Build an OSM-based road network for a wildfire evacuation scenario and    0.00
Droughts in California                                                    0.00
Floods in Texas                                                           0.00
datasets about flooding in Illinois                                       0.00
water datasets                                                            0.00
Water quality datasets in California                                      0.00
What are the main sources of greenhouse gas emissions?                    0.00
What datasets exist for floods?                                           0.00
climate geospatial data                                                   0.00
flood risk geospatial datasets                                            0.00
geospatial datasets dams                                                  0.00
water resource management irrigation                                      0.00
publications by John Smith                                              0.30 ✗
datasets from NASA                                                      0.15 ✗
resources tagged climate                                                0.02 ✗
papers affiliated with USGS                                             0.10 ✗
notebooks written by Shaowen Wang                                       0.32 ✗
What has Anand Padmanabhan published on I-GUIDE?                        0.17 ✗
most popular notebooks                                                  0.07 ✗
trending datasets this month                                            0.13 ✗
resources developed by the University of Illinois                       0.23 ✗
datasets maintained by NOAA                                             0.28 ✗
notebooks that use the SVI dataset                                      0.06 ✗
what publications cite the CyberGIS-Compute paper?                      0.06 ✗
show me resources related to element id 3f2a9c1e                        0.08 ✗
who contributed the FireABM notebook?                                   0.21 ✗
which organizations have uploaded the most datasets?                    0.23 ✗
notebooks categorized as hydrology                                      0.03 ✗
educational resources labeled machine learning                          0.18 ✗
other datasets by the author of the SNAP dataset                        0.08 ✗
notebooks connected to the Pysal Access publication                     0.03 ✗
top viewed OERs                                                         0.07 ✗
weather stations near Chicago                                             0.01
land cover data within 50 miles of Denver                                 0.00
datasets covering 40.1N, 88.2W                                            0.00
elevation data for the Grand Canyon                                       0.00
heat vulnerability in Phoenix neighborhoods                               0.01
crop yield data for the Midwest                                           0.00
hurricane damage along the Gulf Coast                                     0.00
air quality monitoring in Los Angeles County                              0.06
groundwater depletion in the Ogallala aquifer                             0.00
Sentinel-2 imagery over Nairobi                                           0.00
census tracts in Champaign County                                         0.00
wildfire perimeters in northern California 2020                           0.00
flood maps for the Mississippi River basin                                0.00
road networks in Paradise, CA                                             0.04
datasets for Springfield (amb.)                                           0.03
urban heat island studies in Asian megacities                             0.01
coastal erosion in Louisiana                                              0.00
snow cover data for the Rocky Mountains                                   0.00
NASA datasets about drought in Texas                                    0.00 ✗
USGS streamflow data in Iowa                                            0.00 ✗
notebooks by Shaowen Wang about Chicago                                 0.11 ✗
NOAA precipitation datasets near Houston                                0.00 ✗
publications from the University of Illinois on Champaign flooding      0.00 ✗
most popular datasets for California wildfires                          0.04 ✗
resources tagged hydrology covering the Great Lakes                     0.07 ✗
FEMA flood maps for Boone County, Iowa                                  0.04 ✗
notebooks related to the Chicago hospital accessibility dataset         0.04 ✗
USDA crop data for Illinois counties                                    0.00 ✗
papers by Michael Goodchild on geographic information science           0.16 ✗
what is spatial autocorrelation?                                          0.00
how do I compute NDVI from Sentinel-2 bands?                              0.00
machine learning for flood prediction                                     0.00
explain the two-step floating catchment area method                       0.00
datasets about social vulnerability                                       0.03
notebooks on deep learning for land cover classification                  0.02
compare kriging and inverse distance weighting                            0.00
resources about agent-based modeling of evacuation                        0.05
time series of global temperature anomalies (amb.)                        0.00
what is the clay embedding model?                                         0.02
tutorials for GeoPandas                                                   0.04
how does climate change affect crop yields?                               0.00
datasets similar to NLCD land cover (amb.)                              0.00 ✗
open-source tools for hydrological modeling                               0.05
what is the capital of france?                                            0.00
what can you do with satellite imagery?                                   0.00
which embedding models do you have?                                       0.09
what resolution was that?                                                 0.00
show me the code                                                          0.00
can you handle GeoTIFF?                                                   0.00
Embed this drawn region with the gse model (amb.)                         0.03
buffer the hotspot by 2 km and show it on the map (amb.)                  0.00
flood risk geospatial analysis                                            0.07
I-GUIDE Smart Search                                                    0.75 ✗
Build an OSM-based road network for a wildfire evacuation scenario in     0.00
Rank areas that may face higher exposure to potential dam failure r...  0.00 ✗
Acquire precipitation, temperature, wind, humidity, and evapotransp...    0.00
Explain and map major drivers of local water stress using the SIMPL...  0.02 ✗
Map places where heat-related public sentiment or exposure overlaps...    0.00
Identify resources that can detect wildfire threat to transportation i  0.50 ✗
Use available biodiversity and land-use resources to summarize how ter    0.00
Generate a heat map of violent crime in Chicago.                          0.00

                                                                                   \
                                                                       fine-tuned
query
Which Chicago community areas have the poorest spatial accessibility t       0.00
Use the available flood-depth prediction resources to identify require     0.80 ✗
Find flood risk maps for Boone County, Iowa, compare available map yea       0.00
Build an OSM-based road network for a wildfire evacuation scenario and       0.00
Droughts in California                                                       0.00
Floods in Texas                                                              0.00
datasets about flooding in Illinois                                          0.00
water datasets                                                               0.00
Water quality datasets in California                                         0.00
What are the main sources of greenhouse gas emissions?                       0.00
What datasets exist for floods?                                              0.00
climate geospatial data                                                      0.00
flood risk geospatial datasets                                               0.00
geospatial datasets dams                                                     0.00
water resource management irrigation                                         0.00
publications by John Smith                                                   1.00
datasets from NASA                                                           1.00
resources tagged climate                                                     0.99
papers affiliated with USGS                                                  0.99
notebooks written by Shaowen Wang                                            1.00
What has Anand Padmanabhan published on I-GUIDE?                             0.99
most popular notebooks                                                       0.99
trending datasets this month                                                 1.00
resources developed by the University of Illinois                            1.00
datasets maintained by NOAA                                                  1.00
notebooks that use the SVI dataset                                         0.31 ✗
what publications cite the CyberGIS-Compute paper?                           0.98
show me resources related to element id 3f2a9c1e                             0.98
who contributed the FireABM notebook?                                        0.99
which organizations have uploaded the most datasets?                         0.99
notebooks categorized as hydrology                                           0.99
educational resources labeled machine learning                               0.99
other datasets by the author of the SNAP dataset                             0.99
notebooks connected to the Pysal Access publication                          0.99
top viewed OERs                                                              1.00
weather stations near Chicago                                                0.00
land cover data within 50 miles of Denver                                    0.00
datasets covering 40.1N, 88.2W                                               0.00
elevation data for the Grand Canyon                                          0.00
heat vulnerability in Phoenix neighborhoods                                  0.00
crop yield data for the Midwest                                              0.00
hurricane damage along the Gulf Coast                                        0.00
air quality monitoring in Los Angeles County                                 0.00
groundwater depletion in the Ogallala aquifer                                0.00
Sentinel-2 imagery over Nairobi                                              0.00
census tracts in Champaign County                                            0.00
wildfire perimeters in northern California 2020                              0.00
flood maps for the Mississippi River basin                                   0.00
road networks in Paradise, CA                                                0.00
datasets for Springfield (amb.)                                              0.02
urban heat island studies in Asian megacities                                0.00
coastal erosion in Louisiana                                                 0.00
snow cover data for the Rocky Mountains                                      0.00
NASA datasets about drought in Texas                                         0.99
USGS streamflow data in Iowa                                                 0.99

## First tool: accuracy

A request counts as right when the top choice is one of the tools the gold set accepts.

In [5]:
tool_rows = TOOL_SET[:TOOL_LIMIT]
choice = {name: [max(p, key=p.get) for p in res["tools"]] for name, res in results.items()}
pd.DataFrame({name: {"accuracy": sum(c in r["gold"] for c, r in zip(choice[name], tool_rows)) / len(tool_rows),
                     "requests": len(tool_rows)} for name in results}).T.round(3).astype({"requests": int})

            accuracy  requests
vanilla        0.095        42
fine-tuned     0.786        42

## First tool: every answer

The top choice and its probability; ✓ means it is among the gold tools.

In [6]:
def top(probs, gold):
    best, p = max(probs.items(), key=lambda kv: kv[1])
    return f"{'✓' if best in gold else '✗'} {best} {p:.2f}"


pd.DataFrame([{"request": r["request"][:65],
               "files": "yes" if r["context"] != "Attached files: none" else "no",
               "gold": ", ".join(r["gold"]),
               **{name: top(results[name]["tools"][i], r["gold"]) for name in results}}
              for i, r in enumerate(tool_rows)]).set_index("request")

,files,gold,vanilla,fine-tuned
request,,,,
"Pull the boundary of Travis County, Texas.",no,admin_boundary,✗ add_map_layer 0.48,✓ admin_boundary 1.00
"Outline Madison, Wisconsin on the map.",no,admin_boundary,✗ add_map_layer 0.68,✓ admin_boundary 1.00
I need the tracts inside Harris County.,no,admin_boundary,✗ add_map_layer 0.57,✓ admin_boundary 1.00
Show the state line of Nevada.,no,admin_boundary,✗ add_map_layer 0.60,✓ admin_boundary 1.00
Where is the Space Needle? Pin it on the map.,no,geocode_places,✗ add_map_layer 0.68,✗ none 0.20
Get lat/lon for Argonne National Laboratory and Fermilab.,no,geocode_places,✗ add_map_layer 0.59,✓ geocode_places 0.17
"Plot the locations of Stanford, MIT and Caltech.",no,geocode_places,✗ add_map_layer 0.57,✓ geocode_places 0.59
Write and run code that fits a linear regression to 50 random poi,no,execute_code,✗ add_map_layer 0.62,✓ execute_code 0.66
Use Python to convert 12 miles to kilometres and print it.,no,execute_code,✗ add_map_layer 0.55,✓ execute_code 0.64
Generate a synthetic DEM with numpy and compute its slope.,no,execute_code,✗ add_map_layer 0.59,✓ execute_code 0.29
"Give me the prithvi embedding of Denver, Colorado for 2023.",no,"admin_boundary, embed_zones",✗ add_map_layer 0.52,✓ admin_boundary 0.21
"Embed the box -122.5,37.7,-122.35,37.82 with gse.",no,embed_region,✗ add_map_layer 0.66,✓ embed_region 0.31
How different does the area near Lagos look now versus 2019?,no,"embedding_change, geocode_places",✗ add_map_layer 0.57,✗ none 0.91
How alike are central Paris and central Berlin from orbit?,no,"compare_regions, geocode_places",✗ add_map_layer 0.66,✗ none 0.94
"Estimate impervious surface for bbox -90.3,38.55,-90.15,38.7.",no,predict_for_region,✗ add_map_layer 0.48,✗ regionalize 0.22
"Split -97.8,30.2,-97.65,30.35 into 4 similar-looking zones.",no,segment_region,✗ add_map_layer 0.59,✗ regionalize 0.22
Which remote-sensing models can you embed with?,no,list_embedding_models,✓ list_embedding_models 0.56,✓ list_embedding_models 0.95
What does Moran's I measure?,no,none,✗ add_map_layer 0.68,✓ none 1.00
"Great, thank you!",no,none,✗ add_map_layer 0.65,✓ none 0.98
Can you summarise what we found so far?,no,none,✗ add_map_layer 0.59,✓ none 0.99
Look for datasets on wildfire smoke exposure.,no,"request_capability, none",✗ add_map_layer 0.37,✓ request_capability 0.99
Are there any published notebooks on flood inundation mapping?,no,"request_capability, none",✗ add_map_layer 0.56,✓ request_capability 0.86
Map these permits as a heatmap.,yes,"add_map_layer, aggregate_to_grid",✓ add_map_layer 0.65,✓ add_map_layer 0.24
Only show permits issued since 2024.,yes,"detect_time_column, filter_by_time, select_by_attribute",✗ add_map_layer 0.63,✓ detect_time_column 0.99
Is permitting rising or falling month to month?,yes,"detect_time_column, time_series",✗ request_capability 0.67,✓ detect_time_column 0.97
Where did permits concentrate recently compared with earlier year,yes,"detect_time_column, temporal_hotspots",✗ add_map_layer 0.60,✓ detect_time_column 0.95
Keep only the demolition permits.,yes,select_by_attribute,✗ add_map_layer 0.51,✓ select_by_attribute 0.26
Find spatial clusters of permits.,yes,cluster_points,✓ cluster_points 0.42,✓ cluster_points 0.16
Grid the permits into 1 km squares and shade by count.,yes,aggregate_to_grid,✗ add_map_layer 0.61,✓ aggregate_to_grid 0.99
How many permits fall in each zip code? Map it.,yes,count_points_in_areas,✗ add_map_layer 0.59,✓ count_points_in_areas 0.98
Which zip codes gained the most permits from 2023 to 2025?,yes,"detect_time_column, compare_periods",✗ add_map_layer 0.67,✓ detect_time_column 0.79
Is median rent spatially autocorrelated?,yes,global_spatial_autocorrelation,✗ add_map_layer 0.45,✓ global_spatial_autocorrelation 0.60
Map Getis-Ord hot spots of median rent.,yes,local_getis_ord,✗ add_map_layer 0.63,✓ local_getis_ord 0.30
Cluster the zip codes into 5 contiguous regions by rent and popul,yes,regionalize,✗ add_map_layer 0.69,✓ regionalize 0.98
Shade the zip codes by population on the map.,yes,add_map_layer,✓ add_map_layer 0.64,✗ execute_code 0.27
What are the mean and median rent?,yes,summary_statistics,✗ add_map_layer 0.56,✗ spatial_regression 0.13
Merge the zip codes into a single outline.,yes,dissolve_layer,✗ add_map_layer 0.61,✓ dissolve_layer 0.57
Project this to UTM zone 16N.,yes,reproject_vector,✗ add_map_layer 0.59,✓ reproject_vector 0.99
Embed every zip code with tessera for 2024.,yes,embed_zones,✗ add_map_layer 0.69,✗ embed_region 0.38
How far is each well from the nearest stream?,yes,nearest_distance,✗ add_map_layer 0.51,✓ nearest_distance 1.00
Make a 2 km buffer around each well.,yes,buffer_layer,✗ add_map_layer 0.70,✓ buffer_layer 1.00
Cut the roads to the study area.,yes,clip_layer,✗ add_map_layer 0.44,✗ intersect_layers 0.25

## Where the two models disagree

Routing queries where vanilla and fine-tuned Laya reach a different decision on either question, and who matches the gold label.

In [7]:
diff = []
for i, r in enumerate(ROUTER_SET):
    v, f = results["vanilla"]["router"][i], results["fine-tuned"]["router"][i]
    for q in ("graph", "spatial"):
        if (v[q] >= 0.5) != (f[q] >= 0.5):
            diff.append({"query": r["query"][:70], "question": q, "gold": "yes" if r[q] else "no",
                         "vanilla": cell(v[q], r[q]), "fine-tuned": cell(f[q], r[q])})
print(f"{len(diff)} decisions differ out of {2 * len(ROUTER_SET)}")
pd.DataFrame(diff).set_index(["query", "question"])

64 decisions differ out of 192

                                                                                gold  \
query                                                                  question
Use the available flood-depth prediction resources to identify require graph      no
Find flood risk maps for Boone County, Iowa, compare available map yea spatial   yes
Floods in Texas                                                        spatial   yes
datasets about flooding in Illinois                                    spatial   yes
Water quality datasets in California                                   spatial   yes
publications by John Smith                                             graph     yes
datasets from NASA                                                     graph     yes
resources tagged climate                                               graph     yes
papers affiliated with USGS                                            graph     yes
notebooks written by Shaowen Wang                                      graph     yes
What has Anand Padmanabhan published on I-GUIDE?                       graph     yes
most popular notebooks                                                 graph     yes
trending datasets this month                                           graph     yes
resources developed by the University of Illinois                      graph     yes
datasets maintained by NOAA                                            graph     yes
what publications cite the CyberGIS-Compute paper?                     graph     yes
show me resources related to element id 3f2a9c1e                       graph     yes
who contributed the FireABM notebook?                                  graph     yes
which organizations have uploaded the most datasets?                   graph     yes
notebooks categorized as hydrology                                     graph     yes
educational resources labeled machine learning                         graph     yes
other datasets by the author of the SNAP dataset                       graph     yes
notebooks connected to the Pysal Access publication                    graph     yes
top viewed OERs                                                        graph     yes
weather stations near Chicago                                          spatial   yes
datasets covering 40.1N, 88.2W                                         spatial   yes
elevation data for the Grand Canyon                                    spatial   yes
crop yield data for the Midwest                                        spatial   yes
hurricane damage along the Gulf Coast                                  spatial   yes
groundwater depletion in the Ogallala aquifer                          spatial   yes
census tracts in Champaign County                                      spatial   yes
wildfire perimeters in northern California 2020                        spatial   yes
flood maps for the Mississippi River basin                             spatial   yes
datasets for Springfield                                               spatial   yes
urban heat island studies in Asian megacities                          spatial   yes
snow cover data for the Rocky Mountains                                spatial   yes
NASA datasets about drought in Texas                                   graph     yes
                                                                       spatial   yes
USGS streamflow data in Iowa                                           graph     yes
                                                                       spatial   yes
notebooks by Shaowen Wang about Chicago                                graph     yes
                                                                       spatial   yes
NOAA precipitation datasets near Houston                               graph     yes
                                                                       spatial   yes
publications from the University of Illinois on Champaign flooding     graph     yes
                                                                       spatial   yes
most popular datasets for California wildfires                         graph     yes
                                                                       spatial   yes
resources tagged hydrology covering the Great Lakes                    graph     yes
                                                                       spatial   yes
FEMA flood maps for Boone County, Iowa                                 graph     yes
                                                                       spatial   yes
notebooks related to the Chicago hospital accessibility dataset        graph     yes
                                                                       spatial   yes
USDA crop data for Illinois counties                                   graph     yes
                                                                       spatial   yes
papers by Michael Goodchild on geographic information science          graph     yes
tutorials for GeoPandas                                                graph      no
datasets similar to NLCD land cover                                    graph     yes
Build an OSM-based road network for a wildfire evacuation scenario in  spatial   yes
Acquire precipitation, temperature, wind, humidity, and evapotranspira spatial    no
Identify resources that can detect wildfire threat to transportation i graph      no
                                                                       spatial   yes
Generate a heat map of violent crime in Chicago.                       spatial   yes

                                                                                vanilla  \
query                                                                  question
Use the available flood-depth prediction resources to identify require graph       0.03
Find flood risk maps for Boone County, Iowa, compare available map yea spatial   0.18 ✗
Floods in Texas                                                        spatial   0.31 ✗
datasets about flooding in Illinois                                    spatial   0.20 ✗
Water quality datasets in California                                   spatial   0.16 ✗
publications by John Smith                                             graph     0.30 ✗
datasets from NASA                                                     graph     0.15 ✗
resources tagged climate                                               graph     0.02 ✗
papers affiliated with USGS                                            graph     0.10 ✗
notebooks written by Shaowen Wang                                      graph     0.32 ✗
What has Anand Padmanabhan published on I-GUIDE?                       graph     0.17 ✗
most popular notebooks                                                 graph     0.07 ✗
trending datasets this month                                           graph     0.13 ✗
resources developed by the University of Illinois                      graph     0.23 ✗
datasets maintained by NOAA                                            graph     0.28 ✗
what publications cite the CyberGIS-Compute paper?                     graph     0.06 ✗
show me resources related to element id 3f2a9c1e                       graph     0.08 ✗
who contributed the FireABM notebook?                                  graph     0.21 ✗
which organizations have uploaded the most datasets?                   graph     0.23 ✗
notebooks categorized as hydrology                                     graph     0.03 ✗
educational resources labeled machine learning                         graph     0.18 ✗
other datasets by the author of the SNAP dataset                       graph     0.08 ✗
notebooks connected to the Pysal Access publication                    graph     0.03 ✗
top viewed OERs                                                        graph     0.07 ✗
weather stations near Chicago                                          spatial   0.28 ✗
datasets covering 40.1N, 88.2W                                         spatial   0.16 ✗
elevation data for the Grand Canyon                                    spatial   0.50 ✗
crop yield data for the Midwest                                        spatial   0.16 ✗
hurricane damage along the Gulf Coast                                  spatial   0.25 ✗
groundwater depletion in the Ogallala aquifer                          spatial   0.15 ✗
census tracts in Champaign County                                      spatial   0.15 ✗
wildfire perimeters in northern California 2020                        spatial   0.30 ✗
flood maps for the Mississippi River basin                             spatial   0.11 ✗
datasets for Springfield                                               spatial   0.13 ✗
urban heat island studies in Asian megacities                          spatial   0.16 ✗
snow cover data for the Rocky Mountains                                spatial   0.29 ✗
NASA datasets about drought in Texas                                   graph     0.00 ✗
                                                                       spatial   0.15 ✗
USGS streamflow data in Iowa                                           graph     0.00 ✗
                                                                       spatial   0.16 ✗
notebooks by Shaowen Wang about Chicago                                graph     0.11 ✗
                                                                       spatial   0.16 ✗
NOAA precipitation datasets near Houston                               graph     0.00 ✗
                                                                       spatial   0.25 ✗
publications from the University of Illinois on Champaign flooding     graph     0.00 ✗
                                                                       spatial   0.09 ✗
most popular datasets for California wildfires                         graph     0.04 ✗
                                                                       spatial   0.12 ✗
resources tagged hydrology covering the Great Lakes                    graph     0.07 ✗
                                                                       spatial   0.18 ✗
FEMA flood maps for Boone County, Iowa                                 graph     0.04 ✗
                                                                       spatial   0.29 ✗
notebooks related to the Chicago hospital accessibility dataset        graph     0.04 ✗
                                                                       spatial   0.08 ✗
USDA crop data for Illinois counties                                   graph     0.00 ✗
                                                                       spatial   0.09 ✗
papers by Michael Goodchild on geographic information science          graph     0.16 ✗
tutorials for GeoPandas                                                graph       0.04
datasets similar to NLCD land cover                                    graph     0.00 ✗
Build an OSM-based road network for a wildfire evacuation scenario in  spatial   0.10 ✗
Acquire precipitation, temperature, wind, humidity, and evapotranspira spatial     0.29
Identify resources that can detect wildfire threat to transportation i graph     0.50 ✗
                                                                       spatial   0.13 ✗
Generate a heat map of violent crime in Chicago.                       spatial   0.22 ✗

                                                                                fine-tuned
query                                                                  question
Use the available flood-depth prediction resources to identify require graph        0.80 ✗
Find flood risk maps for Boone County, Iowa, compare available map yea spatial        1.00
Floods in Texas                                                        spatial        1.00
datasets about flooding in Illinois                                    spatial        1.00
Water quality datasets in California                                   spatial        1.00
publications by John Smith                                             graph          1.00
datasets from NASA                                                     graph          1.00
resources tagged climate                                               graph          0.99
papers affiliated with USGS                                            graph          0.99
notebooks written by Shaowen Wang                                      graph          1.00
What has Anand Padmanabhan published on I-GUIDE?                       graph          0.99
most popular notebooks                                                 graph          0.99
trending datasets this month                                           graph          1.00
resources developed by the University of Illinois                      graph          1.00
datasets maintained by NOAA                                            graph          1.00
what publications cite the CyberGIS-Compute paper?                     graph          0.98
show me resources related to element id 3f2a9c1e                       graph          0.98
who contributed the FireABM notebook?                                  graph          0.99
which organizations have uploaded the most datasets?                   graph          0.99
notebooks categorized as hydrology                                     graph          0.99
educational resources labeled machine learning                         graph          0.99
other datasets by the author of the SNAP dataset                       graph          0.99
notebooks connected to the Pysal Access publication                    graph          0.99
top viewed OERs                                                        graph          1.00
weather stations near Chicago                                          spatial        1.00
datasets covering 40.1N, 88.2W                                         spatial        1.00
elevation data for the Grand Canyon                                    spatial        1.00
crop yield data for the Midwest                                        spatial        1.00
hurricane damage along the Gulf Coast                                  spatial        1.00
groundwater depletion in the Ogallala aquifer                          spatial        1.00
census tracts in Champaign County                                      spatial        1.00
wildfire perimeters in northern California 2020                        spatial        1.00
flood maps for the Mississippi River basin                             spatial        0.99
datasets for Springfield                                               spatial        1.00
urban heat island studies in Asian megacities                          spatial        1.00
snow cover data for the Rocky Mountains                                spatial        1.00
NASA datasets about drought in Texas                                   graph          0.99
                                                                       spatial        1.00
USGS streamflow data in Iowa                                           graph          0.99
                                                                       spatial        1.00
notebooks by Shaowen Wang about Chicago                                graph          1.00
                                                                       spatial        0.89
NOAA precipitation datasets near Houston                               graph          0.99
                                                                       spatial        1.00
publications from the University of Illinois on Champaign flooding     graph          1.00
                                                                       spatial        1.00
most popular datasets for California wildfires                         graph          1.00
                                                                       spatial        1.00
resources tagged hydrology covering the Great Lakes                    graph          0.99
                                                                       spatial        1.00
FEMA flood maps for Boone County, Iowa                                 graph          0.98
                                                                       spatial        1.00
notebooks related to the Chicago hospital accessibility dataset        graph          0.99
                                                                       spatial        0.95
USDA crop data for Illinois counties                                   graph          0.98
                                                                       spatial        1.00
papers by Michael Goodchild on geographic information science          graph          0.99
tutorials for GeoPandas                                                graph        0.99 ✗
datasets similar to NLCD land cover                                    graph          0.99
Build an OSM-based road network for a wildfire evacuation scenario in  spatial        1.00
Acquire precipitation, temperature, wind, humidity, and evapotranspira spatial      0.82 ✗
Identify resources that can detect wildfire threat to transportation i graph          0.06
                                                                       spatial        1.00
Generate a heat map of violent crime in Chicago.                       spatial        1.00

## Your own inputs

Edit the lists and run the cell. Both models are reloaded, which takes about 10–15 s each on CPU.

In [8]:
MY_QUERIES = ["trending flood datasets from NOAA for Louisiana", "notebooks about kriging"]
MY_REQUESTS = [("Make a 500 m buffer around each school.", "schools.geojson (points; columns: name)"),
               ("Which county has the most wells?", "wells.csv (points; columns: id, lat, lon); counties.geojson (polygons; columns: GEOID, NAME)")]

out = []
for name, path in CHECKPOINTS.items():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model = Agent(str(path), device=DEVICE)
    for q in MY_QUERIES:
        a = model.system_one(q, ROUTER_WORDING[name])["answers"]
        out.append({"input": q, "model": name,
                    "answer": f"P(graph) {a['graph']['noul']:.2f} · P(spatial) {a['spatial']['noul']:.2f}"})
    for req, files in MY_REQUESTS:
        p = model.system_one(f"Attached files: {files}\nRequest: {req}", TOOL_Q,
                             max_len=1600, head_max_len=1400)["answers"]["tool"]["probabilities"]
        out.append({"input": req, "model": name,
                    "answer": " · ".join(f"{k} {v:.2f}" for k, v in sorted(p.items(), key=lambda kv: -kv[1])[:3])})
    del model
pd.DataFrame(out).set_index(["input", "model"])

                                                                                                                           answer
input                                           model
trending flood datasets from NOAA for Louisiana vanilla                                           P(graph) 0.06 · P(spatial) 0.12
notebooks about kriging                         vanilla                                           P(graph) 0.01 · P(spatial) 0.07
Make a 500 m buffer around each school.         vanilla     add_map_layer 0.67 · request_capability 0.09 · count_points_in_are...
Which county has the most wells?                vanilla     add_map_layer 0.49 · cluster_points 0.13 · count_points_in_areas 0.08
trending flood datasets from NOAA for Louisiana fine-tuned                                        P(graph) 0.99 · P(spatial) 1.00
notebooks about kriging                         fine-tuned                                        P(graph) 0.00 · P(spatial) 0.00
Make a 500 m buffer around each school.         fine-tuned            buffer_layer 1.00 · execute_code 0.00 · admin_boundary 0.00
Which county has the most wells?                fine-tuned  admin_boundary 0.29 · select_by_attribute 0.09 · vector_spatial_jo...